name: Geomag Ingest (Swarm only)

on:
  workflow_dispatch: {}
  schedule:
    - cron: "37 4 * * *"   # runs daily at 04:37 UTC

jobs:
  ingest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Swarm ingest
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_KEY: ${{ secrets.SUPABASE_SERVICE_KEY }}
          # For first backfill, set these in "Actions → Variables" or include here as env
          START: ${{ vars.START }}
          END: ${{ vars.END }}
        run: |
          python etl/ingest_swarm_test.py
