name: Geomag Ingest (Swarm only)

on:
  workflow_dispatch: {}
  schedule:
    - cron: "37 4 * * *"   # runs daily at 04:37 UTC

jobs:
  ingest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Swarm ingest (yesterday UTC)
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_KEY: ${{ secrets.SUPABASE_SERVICE_KEY }}
          VIRES_TOKEN: ${{ secrets.VIRES_TOKEN }}
        run: |
          START=$(date -u -d "yesterday 00:00" +'%Y-%m-%dT%H:%M:%SZ')
          END=$(date -u -d "today 00:00" +'%Y-%m-%dT%H:%M:%SZ')
          echo "Window: $START → $END"
          START="$START" END="$END" python etl/ingest_swarm_test.py
